---
alias: Covers
description: >-
  Controls the living room covers and automatically opens/closes them on
  set times.
id: "749d28e5-d9ba-46cb-b1b3-298e378ee450"
mode: queued

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - platform: state
    entity_id: media_player.living_room

variables:
  anchors:
    - &target
      data:
        transition: 5
      target:
        entity_id: light.tv_led

    - &off
      <<: *target
      service: light.turn_off

    - &on
      <<: *target
      service: light.turn_on

action:
  - choose:
      - conditions:
          - alias: "When the tv is playing"
            condition: state
            entity_id: media_player.living_room
            state: "on"
        sequence:
          - *on

    default:
      - *off
