---
alias: "Living Room Vacuum"
description: >-
  Controls the living room vacuum.

id: "88c6f127-5b1f-439e-b911-5a5bed90f45a"
mode: queued

trigger:
  - platform: state
    entity_id:
      - binary_sensor.anyone_home

condition:
  - alias: "When house not in guest mode"
    condition: state
    entity_id: input_boolean.house_mode_guest
    state: "off"

variables:
  anchors:
    - &target
      target:
        entity_id: vacuum.rosie

    - &turn_on
      <<: *target
      service: vacuum.start

    - &return
      <<: *target
      service: vacuum.return_to_base

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: "on"
          - condition: not
            conditions:
              - condition: state
                entity_id: vacuum.rosie
                state: docked
        sequence:
          - *return

      - conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: "off"
        sequence:
          - *turn_on
