---
# Welcome to my Home Assistant configuration!
#
# The configuration.yaml is only used to bootstrap the system.
#
default_config:

# Integrations
recorder: !include integrations/recorder.yaml
http: !include integrations/http.yaml

# Packages
homeassistant:
  packages:
    spa: !include packages/spa/main.yaml
    heating: !include packages/heating/main.yaml
    air_purifier: !include packages/air_purifier/main.yaml
    electrical_blanket: !include packages/electrical_blanket/main.yaml
