---
# Welcome to my Home Assistant configuration!
#
# The configuration.yaml is only used to bootstrap the system.
#
default_config:

automation: !include automations.yaml
automation split: !include_dir_list automation

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: false
  login_attempts_threshold: 5

script: !include_dir_named scripts
recorder: !include integrations/recorder.yaml

input_number: !include entities/helpers/input_numbers.yaml
input_button: !include entities/helpers/input_buttons.yaml

sensor: !include_dir_merge_list entities/sensors/
