version: "3"

services:
  homeassistant:
    container_name: home-assistant
    ports:
      - 8123:8123
    image: homeassistant/home-assistant:$HOME_ASSISTANT_VERSION
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
