---
#
# Small binary sensor to tell me if any media is playing
#
binary_sensor:
  - unique_id: media_playing
    name: Media playing
    icon: fas:play-circle
    device_class: running
    state: "{{ states.media_player | selectattr('state','eq','playing') | list | count > 0 }}"
