---
#
# Small binary sensor to tell me if someone is home or not.
#
binary_sensor:
  - unique_id: anyone_home
    name: Anyone Home
    icon: fas:home
    device_class: presence
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
