---
#
# A washing machine “load running” sensor by monitoring an energy meter connected to the washer
#
sensor:
  - unique_id: washing_machine
    name: Washing Machine
    icon: mdi:washing-machine
    state: >-
      {% if is_state("sensor.wasmachine_washer_machine_state", "run") -%}
        on
      {%- else -%}
        off
      {%- endif %}
    attributes:
      job: >-
        {% if is_state("sensor.wasmachine_washer_machine_state", "run") -%}
          {{ states("sensor.wasmachine_washer_job_state")|capitalize }}
        {%- else -%}
          none
        {%- endif %}
      completion_time: >-
        {% if is_state("sensor.wasmachine_washer_machine_state", "run") -%}
          {{ as_timestamp(states("sensor.wasmachine_washer_completion_time"))| timestamp_custom('%H:%M') }}
        {%- else -%}
          0
        {%- endif %}
