open_blinds:
  alias: Open Blinds
  sequence:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.sonoff_1000bc8cb8_2
          - switch.sonoff_1000bc8bca_2
    - service: switch.turn_on
      target:
        entity_id:
          - switch.sonoff_1000bc8cb8_1
          - switch.sonoff_1000bc8bca_1
    - delay:
        seconds: 40
    - service: cover.set_cover_position
      target:
        entity_id: cover.covers
      data:
        position: 100
    - service: script.pause_blinds
  mode: single
