- name: Away
  entities:
    light.dining_table:
      state: "off"
    light.reading_lamp:
      state: "off"
    light.chandelier:
      state: "off"
    media_player.badkamer:
      state: "off"
    media_player.living_speaker:
      state: "off"
    media_player.samsung_tv:
      state: "off"
    media_player.kantoor:
      state: "off"
    media_player.hub:
      state: "off"
  icon: fas:lock
