- name: Goodnight
  entities:
    light.chandelier:
      state: "off"
    light.led:
      state: "off"
    light.reading_lamp:
      state: "off"
    light.eettafel:
      state: "off"
    media_player.samsung_tv:
      state: "off"
  icon: fas:moon
