- platform: template
  switches:
    tv:
      friendly_name: Tv
      value_template: "{{ is_state('media_player.living_room', 'on') }}"
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: media_player.tv
      turn_off:
        service: media_player.turn_off
        target:
          entity_id: media_player.living_room
      icon_template: >-
        {% if is_state('media_player.living_room', 'on') %}
          mdi:televsion
        {% else %}
          mdi:television-off
        {% endif %}
