heating:
  template:
    - base
    - circle
    - icon_radiator
  variables:
    attributes: >
      [[[ return entity === undefined || states[entity.entity_id].attributes; ]]]
    consider_on: >
      [[[
        return entity.attributes.hvac_action == 'heating'
      ]]]
    identifier: >
      [[[
        return entity.entity_id.split('.').pop()
      ]]]
  state_display: >
    [[[
      if (entity != undefined) {
        if (variables.state === 'unavailable') {
          return 'Unavailable'
        }

        return `${variables.attributes.current_temperature}째 <small>(${variables.attributes.temperature}째)</small>`;
      }
      return 'Unknown';
    ]]]
  custom_fields:
    circle: >
      [[[
        if (variables.state === 'unavailable') {
          return `
            <svg viewBox="0 0 326.157 326.157" fill="">
              <path d="M206.342,275.032c-8.284,0-15,6.716-15,15v21.124c0,8.284,6.716,15,15,15s15-6.716,15-15v-21.124 C221.342,281.748,214.626,275.032,206.342,275.032z"/>
              <path d="M311.158,191.343l-21.125-0.001c-0.001,0,0,0-0.001,0c-8.283,0-15,6.716-15,14.999 c0,8.284,6.715,15.001,14.999,15.001l21.125,0.001c0.001,0,0.001,0,0.001,0c8.283,0,15-6.716,15-14.999 C326.157,198.06,319.442,191.343,311.158,191.343z"/>
              <path d="M276.127,254.913c-5.858-5.858-15.355-5.857-21.214-0.001c-5.857,5.858-5.858,15.355-0.001,21.214 l14.938,14.938c2.93,2.93,6.768,4.394,10.607,4.394c3.838,0,7.678-1.465,10.607-4.393c5.857-5.858,5.858-15.355,0.001-21.214 L276.127,254.913z"/>
              <path d="M119.813,51.124c8.284,0,15-6.716,15-15V15c0-8.284-6.716-15-15-15c-8.284,0-15,6.716-15,15v21.124 C104.813,44.408,111.529,51.124,119.813,51.124z"/>
              <path d="M36.124,134.815c8.284,0,15-6.716,15-14.999c0-8.284-6.715-15.001-15-15.001L15,104.814h0 c-8.284,0-15,6.716-15,14.999C0,128.097,6.715,134.814,15,134.814L36.124,134.815C36.124,134.815,36.124,134.815,36.124,134.815z" />
              <path d="M50.029,71.243c2.929,2.93,6.768,4.394,10.607,4.394c3.838,0,7.678-1.465,10.607-4.393 c5.858-5.858,5.858-15.355,0-21.214L56.305,35.092c-5.857-5.858-15.355-5.857-21.213-0.001c-5.858,5.858-5.858,15.355,0,21.214 L50.029,71.243z"/>
              <path d="M194.898,237.323c5.858-5.857,5.858-15.355,0-21.213c-5.857-5.857-15.355-5.857-21.213,0l-42.423,42.423 c-0.002,0.002-0.003,0.003-0.005,0.005c-17.543,17.545-46.092,17.546-63.638,0s-17.546-46.095,0-63.641l42.426-42.426 c5.858-5.857,5.858-15.355,0-21.213c-5.857-5.857-15.355-5.857-21.213,0l-42.426,42.426c-29.243,29.242-29.243,76.823,0,106.066 c14.166,14.166,33,21.967,53.032,21.967c0.001,0,0,0,0.001,0c20.032,0,38.867-7.802,53.032-21.967 c0.002-0.002,0.003-0.003,0.005-0.005L194.898,237.323z"/>
              <path d="M279.75,46.405c-14.164-14.165-32.998-21.967-53.031-21.967c-0.001,0,0.001,0-0.001,0 c-20.032,0-38.867,7.802-53.032,21.967l-0.001,0.001l-0.001,0.001l-42.425,42.426c-5.858,5.857-5.858,15.355,0,21.213 c2.929,2.929,6.768,4.394,10.606,4.394c3.839,0,7.678-1.465,10.607-4.394l42.425-42.426l0.001-0.001l0.001-0.001 c8.499-8.499,19.8-13.18,31.82-13.18c12.02,0,23.319,4.681,31.818,13.18c17.546,17.546,17.546,46.095,0,63.641l-42.426,42.426 c-5.858,5.857-5.858,15.355,0,21.213c2.929,2.929,6.768,4.394,10.607,4.394c3.839,0,7.678-1.465,10.606-4.394l42.426-42.426 C308.993,123.23,308.993,75.648,279.75,46.405z"/>
            </svg>
          `;
        }

        if (variables.state !== 'auto') {
          return `
            <svg viewBox="0 0 50 50">
              <circle cx="25" cy="25" r="20.5" stroke="#aa4500" stroke-width="1.5" fill="none" />
              <text x="50%" y="54%" fill="#aa4500" font-size="14" text-anchor="middle" alignment-baseline="middle" dominant-baseline="middle">MAN</text>
            </svg>
          `;
        }
      ]]]
  styles:
    card:
      - fontStyle: >
          [[[
            if (variables.state === 'unavailable') {
              return 'italic';
            }
          ]]]
    custom_fields:
      circle:
        - width: >
            [[[ return variables.state === 'unavailable' ? '40%' : '70%' ]]]
        - fill: "#aa4500"
  tap_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: >
        [[[ return entity.attributes.friendly_name; ]]]
      style:
        .: |
          :host .content {
            width: 680px;
            max-width: 90vw;
          }
        hui-entities-card:
          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
      card:
        type: entities
        entities:
          - type: attribute
            entity: >
              [[[ return entity.entity_id; ]]]
            attribute: current_temperature
            suffix: 째C
            name: Temperatuur
            icon: mdi:home-thermometer

          - type: custom:slider-entity-row
            min: >
              [[[ return entity.attributes.min_temp ]]]
            max: >
              [[[ return entity.attributes.max_temp ]]]
            step: >
              [[[ return entity.attributes.target_temp_step ]]]
            entity: >
              [[[ return entity.entity_id; ]]]
            suffix: 째C
            grow: true
            name: Ingesteld op
            icon: mdi:thermometer

          - type: attribute
            entity: >
              [[[ return entity.entity_id; ]]]
            attribute: current_humidity
            suffix: "%"
            name: Luchtvochtigheid
            icon: mdi:water-percent

          - entity: >
              [[[ return `binary_sensor.${variables.identifier}_open_window`; ]]]
            name: Raam

          - entity: >
              [[[ return `binary_sensor.${variables.identifier}_link`; ]]]
            name: Connectiviteit

          - type: custom:bar-card
            width: 30%
            height: 2em
            decimal: 0
            unit_of_measurement: "%"
            positions:
              icon: outside
              indicator: "off"
              name: outside
            severity:
              - color: "#303435"
                from: 0
                to: 89
              - color: "#6d2525"
                from: 90
                to: 200
            entity_row: true
            entities:
              - entity: >
                  [[[ return `sensor.${variables.identifier}_heating`; ]]]
                name: Verwarmen
                tap_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: >
                      [[[ return `sensor.${variables.identifier}_heating`; ]]]

          - type: conditional
            conditions:
              - entity: >
                  [[[ return entity.entity_id; ]]]
                state_not: auto
              - entity: >
                  [[[ return entity.entity_id; ]]]
                state_not: unavailable
            row:
              type: divider

          - type: conditional
            conditions:
              - entity: >
                  [[[ return entity.entity_id; ]]]
                state_not: auto
              - entity: >
                  [[[ return entity.entity_id; ]]]
                state_not: unavailable
            row:
              type: custom:hui-horizontal-stack-card
              cards:
                - type: custom:button-card
                  name: Schema hervatten
                  icon: mdi:reload
                  tap_action:
                    action: call-service
                    service: climate.set_hvac_mode
                    service_data:
                      entity_id: >
                        [[[ return entity.entity_id; ]]]
                      hvac_mode: auto
                  template: icon_name

        footer:
          type: custom:mini-graph-card
          entities:
            - color: "#ffc500"
              entity: >
                [[[ return `sensor.${variables.identifier}_temperature`; ]]]
          align_state: left
          group: false
          points_per_hour: 1
          line_width: 3
          hour24: true
          show:
            {
              fill: fade,
              icon: false,
              name: false,
              state: false,
              name_adaptive_color: true,
              points: false,
              extrema: false,
              legend: false,
              average: false,
            }
          tap_action:
            action: none

  hold_action:
    action: none
