- name: Away
  entities:
    light.chandelier:
      state: "off"
    light.reading_lamp:
      state: "off"
    light.luchter:
      state: "off"
    group.thermostats:
      state: "auto"
      preset_mode: away
  icon: mdi:shield-lock
