- name: Watching TV
  entities:
    light.leeslamp:
      state: "on"
      brightness: 1
      color_temp: 450
    light.eettafel:
      state: "off"
    light.luchter:
      state: "off"
  icon: mdi:television-classic
