- platform: template
  covers:
    covers:
      device_class: blind
      icon_template: "{{ 'mdi:window-shutter-open' if is_state('cover.covers', 'open') else 'mdi:window-shutter' }}"
      friendly_name: "Blinds"
      open_cover:
        service: script.open_blinds
      close_cover:
        service: script.close_blinds
      stop_cover:
        service: script.pause_blinds
