platform: afvalinfo
resources:
  - type: gft
    friendly_name: Groente Fruit en Tuinafval
  - type: papier
    friendly_name: Papier
  - type: restafval
    friendly_name: Restafval
  - type: trash_type_today
    friendly_name: Waste today
  - type: trash_type_tomorrow
    friendly_name: Waste tomorrow

location: !secret wastecollector_city
postcode: !secret wastecollector_zip
streetnumber: !secret wastecollector_number
