dining_table_brightness:
  name: Dining table brightness
  min: 0
  max: 255
  step: 1

dining_table_color_temp:
  name: Dining table color temperature
  min: 153
  max: 500
  step: 1

reading_lamp_brightness:
  name: Reading lamp brightness
  min: 0
  max: 255
  step: 1

reading_lamp_color_temp:
  name: Reading lamp color temperature
  min: 153
  max: 500
  step: 1
