- alias: conditional_media_playing
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - media_player.tv
        - media_player.spotify
        - media_player.emby_chrome_2
      to: playing
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.conditional_media
      data:
        option: >
          {{ trigger.to_state.name }}

- alias: conditional_media_paused_idle
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - media_player.tv
        - media_player.spotify
        - media_player.emby_chrome_2
      to: ["off", "idle", "standby"]
    - platform: state
      entity_id:
        - media_player.tv
        - media_player.spotify
        - media_player.emby_chrome_2
      to: paused
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.conditional_media
      data:
        option: >
          {% set media_players =
            [states.media_player.tv, states.media_player.spotify,
              states.media_player.emby_chrome_2] %}
          {% if media_players | selectattr('state','eq','playing') | list | count == 0 %}
            {% if media_players | selectattr('state','eq','paused') | list | count == 0 %}
            Upcoming media
            {% else %}
            {{ media_players | selectattr('state','eq','paused') | map(attribute='name') | max }}
            {% endif %}
          {% else %}
          {{ media_players | selectattr('state','eq','playing') | map(attribute='name') | max }}
          {% endif %}

- alias: conditional_media_all_off
  initial_state: true
  trigger:
    - platform: template
      value_template: >
        {{ is_state('media_player.tv', 'idle') and
        is_state('media_player.spotify', 'idle') and
        is_state('media_player.emby_chrome_2', 'off')
        or
        is_state('media_player.tv', 'off') and
        is_state('media_player.spotify', 'off') and
        is_state('media_player.emby_chrome_2', 'off') }}
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.conditional_media
      data:
        option: Upcoming media
