- alias: Home scene selected
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_scene
      to: Home
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.home
    - delay:
        minutes: 5
    - service: input_select.select_option
      data:
        option: None

- alias: Away scene selected
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_scene
      to: Away
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.away
    - delay:
        minutes: 5
    - service: input_select.select_option
      data:
        option: None

- alias: Watching TV scene selected
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_scene
      to: Watching TV
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.watching_tv
    - delay:
        minutes: 5
    - service: input_select.select_option
      data:
        option: None

- alias: Dinner scene selected
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_scene
      to: Dinner
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.dinner
    - delay:
        minutes: 5
    - service: input_select.select_option
      data:
        option: None

- alias: Goodnight scene selected
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.active_scene
      to: Goodnight
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.goodnight
    - delay:
        minutes: 5
    - service: input_select.select_option
      data:
        option: None
