binary_sensor:
  - unique_id: media_players_active
    name: Media player activity
    icon: fas:play-circle
    delay_off:
      seconds: 30
    state: >
      {% set media_players = [
        states.media_player.kantoor,
        states.media_player.tv,
        states.media_player.hub,
        states.media_player.home,
        states.media_player.badkamer,
      ] %}
      {{ media_players | selectattr('state','eq','playing') | list | count > 0 }}


  - unique_id: anyone_home
    name: Anyone Home
    icon: fas:home
    device_class: presence
    state: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
