---
sensor:
  - unique_id: greeting
    name: Greeting
    state: |
      <b>
      {%- set time = now().hour %}
      {%- if time <= 1 -%} Goeienacht {{'\U0001F611'}}
      {%- elif time <= 3 -%} Goeienacht {{'\U0001F62A'}}
      {%- elif time <= 5 -%} Goeienacht {{'\U0001F634'}}
      {%- elif time <= 7 -%} Goeiemorgen {{'\U0001F4A9'}}
      {%- elif time <= 9 -%} Goeiemorgen {{'\u2615\uFE0F'}}
      {%- elif time <= 10 -%} Goeiemorgen {{'\U0001F642'}}
      {%- elif time <= 13 -%} Goeiedag {{'\U0001F60A'}}
      {%- elif time <= 15 -%} Goeiedag {{'\U0001F60E'}}
      {%- elif time <= 17 -%} Goeiedag {{'\U0001F44B\U0001F3FB'}}
      {%- elif time <= 19 -%} Goeieavond {{'\U0001F44B\U0001F3FB'}}
      {%- elif time <= 22 -%} Goeieavond {{'\U0001F60C'}}
      {%- elif time <= 23 -%} Goeieavond {{'\U0001F974'}}
      {%- else %} Goeieavond {{'\U0001F974'}}
      {%- endif -%}
      </b>
