- platform: version
  name: hass_version_installed
  source: local

- platform: version
  name: hass_version_latest
  source: container

- platform: version
  name: hass_version_latest_beta
  source: container
  beta: true

- platform: uptime

- platform: rest
  name: hass_release_notes
  resource: https://api.github.com/repos/home-assistant/core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: rest
  name: hass_release_notes_rc
  resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
  scan_interval: 21600

- platform: dnsip

- platform: template
  sensors:
    hass_version:
      icon_template: mdi:home-assistant
      friendly_name_template: >
        Versie
      value_template: >
        {{ 'latest' if states('sensor.hass_version_installed') ==
        states('sensor.hass_version_latest') else states('sensor.hass_version_installed') }}
