- platform: template
  sensors:
    people_home:
      friendly_name: "Number of people at home"
      value_template: >
        {{ [states.person.helena_user, states.person.nancy] | selectattr('state', '==', 'home') | list | count }}
