alias: Auto close covers
id: auto_close_covers
mode: single

trigger:
  - platform: state
    entity_id:
      - input_boolean.night_mode
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: cover.living_room
    state: open
action:
  - service: cover.close_cover
    target:
      entity_id: cover.living_room
