alias: Auto open covers
id: auto_open_covers
mode: single

trigger:
  - platform: state
    entity_id:
      - input_boolean.night_mode
    from: "on"
    to: "off"
condition:
  - condition: state
    entity_id: cover.living_room
    state: closed
action:
  - service: cover.open_cover
    target:
      entity_id: cover.living_room
