- alias: Coming home
  id: coming_home
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: "on"
  action:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"

    - scene: scene.home
