- alias: Dining table brightness
  trigger:
    platform: state
    entity_id: light.dining_table
    from: "off"
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.dining_table
    data_template:
      brightness: >
        {% if now().hour > 20 %}50
        {% elif now().hour < 5 %}20
        {% elif now().hour < 8 %}50
        {% else %}200
        {% endif %}
      color_temp: >
        {% if now().hour > 20 %}370
        {% elif now().hour < 8 %}370
        {% else %}153
        {% endif %}
