alias: Turn off night mode
id: turn_off_night_mode
mode: single

trigger:
  - platform: time_pattern
    minutes: "/10"

condition:
  - condition: or
    conditions:
      - condition: time
        after: "07:30:00"
      - condition: sun
        after: sunrise

action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.night_mode
