alias: Turn on night mode
id: turn_on_night_mode
mode: single

trigger:
  - platform: time
    at: "20:00:00"

  - platform: sun
    event: sunset
    offset: 30

condition:
  - condition: state
    entity_id: cover.living_room
    state: open

action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.night_mode
