alias: Turn off night mode
id: turn_off_night_mode
mode: single

trigger:
  - platform: time
    at: "07:30:00"

  - platform: sun
    event: sunrise

condition:
  - condition: state
    entity_id: cover.living_room
    state: closed

action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.night_mode
