alias: Turn on night mode
id: turn_on_night_mode
mode: single

trigger:
  - platform: time_pattern
    minutes: "/10"

condition:
  - condition: or
    conditions:
      - condition: time
        after: "20:00:00"
      - condition: sun
        after: sunset
        after_offset: 30

action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.night_mode
