alias: TV backlight off
id: tv_backlight_off
mode: single

trigger:
  - platform: state
    entity_id: media_player.samsung_tv
    to: "off"

action:
  - service: light.turn_off
    target:
      entity_id: light.led
