- alias: TV backlight on
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.led

- alias: TV backlight off
  mode: single
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.led
