alias: Heating badkamer home
id: heating_badkamer_home
mode: single

trigger:
  - minutes: /5
    platform: time_pattern

condition:
  - condition: state
    entity_id: input_select.heating_modes
    state: Home
  - condition: state
    entity_id: input_boolean.custom_heating
    state: "off"

action:
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "08:00:00"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              entity_id: climate.badkamer
          - service: climate.set_temperature
            data:
              temperature: 22
            target:
              entity_id: climate.badkamer
      - conditions:
          - condition: time
            after: "08:00:00"
            before: "18:00:00"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              entity_id: climate.badkamer
          - service: climate.set_temperature
            data:
              temperature: 18
            target:
              entity_id: climate.badkamer
      - conditions:
          - condition: time
            after: "18:00:00"
            before: "19:30:00"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              entity_id: climate.badkamer
          - service: climate.set_temperature
            data:
              temperature: 22
            target:
              entity_id: climate.badkamer
    default:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.badkamer
