alias: Heating woonkamer away
id: heating_woonkamer_away
mode: single

trigger:
  - platform: state
    entity_id:
      - input_select.heating_modes
    to: Away

condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"

action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: "off"
    target:
      entity_id: climate.woonkamer
