alias: Heating slaapkamer_ouders working at home
id: heating_slaapkamer_ouders_working_at_home
mode: single

trigger:
  - minutes: /5
    platform: time_pattern

condition:
  - condition: state
    entity_id: input_select.heating_modes
    state: Working at home
  - condition: state
    entity_id: input_boolean.custom_heating
    state: "off"

action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: "off"
    target:
      entity_id: climate.slaapkamer_ouders
