alias: Heating slaapkamer_kids working at home
id: heating_slaapkamer_kids_working_at_home
mode: single

trigger:
  - platform: state
    entity_id:
      - input_select.heating_modes
    to: Working at home

action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: "off"
    target:
      entity_id: climate.slaapkamer_lore
