alias: Heating slaaclimate.slaapkamer_ouders home
id: heating_slaaclimate.slaapkamer_ouders_home
mode: single

trigger:
  - minutes: /5
    platform: time_pattern

condition:
  - condition: state
    entity_id: input_select.heating_modes
    state: Home

action:
  - choose:
      - conditions:
          - condition: time
            after: "20:00:00"
            before: "08:00:00"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              entity_id: climate.slaapkamer_ouders
          - service: climate.set_temperature
            data:
              temperature: 18
            target:
              entity_id: climate.slaapkamer_ouders
    default:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.slaapkamer_ouders
