alias: Heating kantoor working at home
id: heating_kantoor_working_at_home
mode: single

trigger:
  - minutes: /5
    platform: time_pattern

condition:
  - condition: state
    entity_id: input_select.heating_modes
    state: Working at home
  - condition: state
    entity_id: input_boolean.custom_heating
    state: "off"

action:
  - choose:
      - conditions:
          - condition: time
            after: "08:30:00"
            before: "17:00:00"
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              entity_id: climate.kantoor
          - service: climate.set_temperature
            data:
              temperature: 21.5
            target:
              entity_id: climate.kantoor
    default:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.kantoor
