title: Overview
path: overview
icon: fas:home
type: custom:masonry-layout
layout:
  max_cols: 3
cards:
  # ===
  # Weather
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: custom_card_greeting
        entity: sensor.greeting

      - type: custom:button-card
        template: card_weather
        entity: weather.openweathermap
        variables:
          ulm_card_weather_name: " "
          ulm_card_weather_primary_info:
            - wind_speed
            - precipitation_probability
          ulm_card_weather_backdrop:
            fade: true

      - type: custom:sun-card

  # ===
  # Calendar
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Kalender

      - type: custom:atomic-calendar-revive
        showWeekDay: true
        showLocation: true
        sortByStartTime: true
        maxDaysToShow: 3
        showEventIcon: true
        showCalendarName: true
        showProgressBar: true
        entities:
          - entity: calendar.afval
            icon: fas:trash-alt
            color: var(--google-blue)
            name: Afval
          - entity: calendar.gezin
            icon: fas:users
            name: Gezin
            color: var(--google-green)
          - entity: calendar.feestdagen_in_belgie
            icon: fas:calendar-day
            name: Gezin
            color: var(--google-yellow)
          - entity: calendar.work
            icon: fas:briefcase
            name: Gezin
            color: var(--google-red)
          - entity: calendar.persoonlijk
            icon: fas:user
            color: var(--google-violet)
            name: Helena
          - entity: calendar.nancy
            icon: fas:user
            color: var(--google-blue)
            name: Nancy

  - type: vertical-stack
    cards:
      # ===
      # Media
      # ===
      - type: conditional
        conditions:
          - entity: binary_sensor.media_player_activity
            state: "on"
        card:
          type: vertical-stack
          cards:
            - type: custom:button-card
              template: card_title
              name: Media

            - type: grid
              columns: 2
              square: false
              cards:
                # Tv
                - type: conditional
                  conditions:
                    - entity: media_player.tv
                      state: playing
                  card:
                    type: "custom:button-card"
                    template: card_media_player
                    entity: media_player.tv
                    name: Tv
                    variables:
                      ulm_card_media_player_enable_art: true
                      ulm_card_media_player_enable_controls: true
                      ulm_card_media_player_player_controls_entity: media_player.samsung_tv

                # Kantoor
                - type: conditional
                  conditions:
                    - entity: media_player.kantoor
                      state: playing
                  card:
                    type: "custom:button-card"
                    template: card_media_player
                    entity: media_player.kantoor
                    name: Kantoor
                    variables:
                      ulm_card_media_player_enable_art: true
                      ulm_card_media_player_enable_controls: true

                # Hub
                - type: conditional
                  conditions:
                    - entity: media_player.hub
                      state: playing
                  card:
                    type: "custom:button-card"
                    template: card_media_player
                    entity: media_player.hub
                    name: Hub
                    variables:
                      ulm_card_media_player_enable_art: true
                      ulm_card_media_player_enable_controls: true

                # Badkamer
                - type: conditional
                  conditions:
                    - entity: media_player.badkamer
                      state: playing
                  card:
                    type: "custom:button-card"
                    template: card_media_player
                    entity: media_player.badkamer
                    name: Badkamer
                    variables:
                      ulm_card_media_player_enable_art: true
                      ulm_card_media_player_enable_controls: true

                # Home
                - type: conditional
                  conditions:
                    - entity: media_player.home
                      state: playing
                  card:
                    type: "custom:button-card"
                    template: card_media_player
                    entity: media_player.home
                    name: Woonkamer
                    variables:
                      ulm_card_media_player_enable_art: true
                      ulm_card_media_player_enable_controls: true

      # ===
      # Quick controls
      # ===
      - type: custom:button-card
        template: card_title
        name: Apparaten

      - type: grid
        square: false
        columns: 2
        cards:
          - type: "custom:button-card"
            template: card_light
            entity: light.dining_table
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_force_background_color: true
          - type: "custom:button-card"
            template: card_light
            entity: light.reading_lamp
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_force_background_color: true
          - type: "custom:button-card"
            template: card_light
            entity: light.led
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_force_background_color: true
          - type: "custom:button-card"
            template: card_light
            entity: light.chandelier
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_force_background_color: true
          - type: "custom:button-card"
            template: card_power_outlet
            entity: switch.babyfoon_noor
            variables:
              ulm_card_power_outlet_icon: mdi:cradle
          - type: "custom:button-card"
            template: card_cover
            entity: cover.living_room
            variables:
              ulm_card_cover_enable_controls: true
          - type: custom:button-card
            template: card_vacuum
            entity: vacuum.roomba
