title: Climate
path: climate
icon: fas:cloud-sun
type: custom:masonry-layout
layout:
  max_cols: 3
  reflow: true
cards:
  # ===
  # Thermostat
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Thermostaat

      - type: "custom:auto-entities"
        card:
          type: grid
          columns: 2
          square: false
        card_param: "cards"
        filter:
          include:
            - domain: climate
              options:
                type: custom:button-card
                template: card_thermostat
                entity: this.entity_id
                variables:
                  ulm_card_thermostat_enable_background_color: true
                  ulm_card_thermostat_enable_controls: true
                  ulm_card_thermostat_enable_popup: true
  # ===
  # Temperature
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Temperatuur

      - type: "custom:auto-entities"
        card:
          type: entities
        filter:
          include:
            - entity_id: sensor.*_temperature
              integration: tado

  # ===
  # Temperature
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Temperatuur

      - type: "custom:auto-entities"
        card:
          type: entities
        filter:
          include:
            - entity_id: sensor.*_humidity
              integration: tado
