title: Devices
path: devices
icon: fas:laptop-house
type: custom:masonry-layout
layout:
  max_cols: 3
  reflow: true
cards:
  # ===
  # Lights
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Lichten

      - type: "custom:auto-entities"
        card:
          type: grid
          columns: 2
          square: false
        card_param: "cards"
        filter:
          include:
            - domain: light
              options:
                type: "custom:button-card"
                template: card_light
                entity: this.entity_id
                variables:
                  ulm_card_light_enable_slider: true
                  ulm_card_light_enable_color: true
                  ulm_card_light_force_background_color: true
          exclude:
            - entity_id: "light.reading_lamp_*"
            - entity_id: "light.hanglamp_*"
            - entity_id: "light.camera_*"

  # ===
  # Media
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Media

      - type: "custom:auto-entities"
        card:
          type: grid
          columns: 2
          square: false
        card_param: "cards"
        filter:
          include:
            - domain: media_player
              options:
                type: "custom:button-card"
                template: card_media_player
                entity: this.entity_id
                variables:
                  ulm_card_media_player_enable_art: true
                  ulm_card_media_player_enable_controls: true

  # ===
  # Switches
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Schakelaars

      - type: "custom:auto-entities"
        card:
          type: grid
          columns: 2
          square: false
        card_param: "cards"
        filter:
          include:
            - domain: switch
              options:
                type: "custom:button-card"
                template: card_power_outlet
                entity: this.entity_id
          exclude:
            - state: unavailable
            - entity_id: "switch.cover_*"
            - entity_id: "switch.camera_*"

  # ===
  # Others
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Andere

      - type: grid
        square: false
        columns: 2
        cards:
          - type: "custom:button-card"
            template: card_cover
            entity: cover.living_room
            variables:
              ulm_card_cover_enable_controls: true
          - type: custom:button-card
            template: card_vacuum
            entity: vacuum.roomba
