title: Configuration
path: configuration
icon: fas:cog
type: custom:horizontal-layout
layout:
  max_cols: 3
cards:
  # ===
  # Modes
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Modi

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_input_boolean
            entity: input_boolean.guest_mode

          - type: "custom:button-card"
            template: card_input_boolean
            entity: input_boolean.night_mode

          - type: "custom:button-card"
            template: card_input_boolean
            entity: input_boolean.custom_heating

  # ===
  # Links
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Links

      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /profile
              ulm_card_navigate_title: Profile
              ulm_card_navigate_icon: fas:user

          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /config
              ulm_card_navigate_title: Configuration
              ulm_card_navigate_icon: fas:cog
        name: Verwarming

  # ===
  # Heating modes
  # ===
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Verwarming

      - type: grid
        columns: 3
        square: false
        cards:
          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.heating_modes
            name: Home
            icon: fas:home
            variables:
              ulm_card_vertical_button_state: Home
              ulm_card_vertical_button_color: green

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.heating_modes
            name: Working at home
            icon: fas:briefcase
            variables:
              ulm_card_vertical_button_state: Working at home
              ulm_card_vertical_button_color: yellow

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.heating_modes
            name: Away
            icon: fas:running
            variables:
              ulm_card_vertical_button_state: Away
              ulm_card_vertical_button_color: red
