action: fire-dom-event
browser_mod:
  command: popup
  title: Information
  style:
    .: |
      :host .content {
        width: calc(385px + 385px);
        max-width: 90vw;
      }
    layout-card:
      $grid-layout$:
        hui-entities-card:
          $: |
            .card-content {
              padding: 1.5em 2.7em 2.3em 2em;
            }
            ha-card {
              animation: border 1s forwards;
              border-radius: 0;
            }
            @keyframes border {
              0%, 100% {
                border-right: 1px solid rgba(0, 0, 0, 0.3);
              }
            }
            /* phone */
            @media screen and (max-width: 800px) {
              ha-card {
                animation: none;
              }
            }
          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        "hass nas"
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(2, 1fr)
          grid-template-areas: |
            "hass"
            "nas"
    cards:
      #################################################
      #                                               #
      #                HOME ASSISTANT                 #
      #                                               #
      #################################################

      - type: entities
        view_layout:
          grid-area: hass
        title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
            }
        entities:
          - entity: sensor.hass_version

          - entity: sensor.uptime

          - type: custom:hui-horizontal-stack-card
            cards:
              - type: custom:button-card
                name: Home Assistant
                icon: mdi:reload
                tap_action:
                  services: |
                    [[[
                      hass.callService('browser_mod', 'toast', {
                        message: 'Home Assistant herstarten...'
                      });
                      hass.callService('homeassistant', 'restart');
                    ]]]
                template: icon_name

      #################################################
      #                                               #
      #                      NAS                      #
      #                                               #
      #################################################

      - type: entities
        view_layout:
          grid-area: nas
        title: Synology DS218
        show_header_toggle: false
        card_mod:
          class: header
          style:
            .: |
              ha-card {
                animation: none !important;
                margin: 0px !important;
              }
            mini-graph-card:
              $: |
                ha-card {
                  padding: 0px !important;
                }
            hui-horizontal-stack-card:
              $:
                .: |
                  #root {
                    margin-top: 1em;
                    margin-right: 1.5em;
                  }
                  #root > * {
                    flex: none !important;
                  }
                hui-entities-card:
                  $:
                    .: |
                      #states {
                        padding: 0;
                      }
                    hui-sensor-entity-row:
                      $hui-generic-entity-row$: |
                        .info {
                          margin: 0 8px 0 8px !important;
                        }
        entities:
          - entity: sensor.svnas_volume_1_status
            name: Status

          - entity: binary_sensor.svnas_security_status
            name: Veiligheidsstatus

          - entity: sensor.svnas_volume_1_average_disk_temp
            name: Temperatuur

          # - entity: sensor.svnas_last_boot
          #   name: Laatst herstart

          - type: custom:bar-card
            width: 55%
            height: 2em
            decimal: 0
            unit_of_measurement: "%"
            positions:
              icon: outside
              indicator: "off"
              name: outside
            severity:
              - color: "#303435"
                from: 0
                to: 89
              - color: "#6d2525"
                from: 90
                to: 200
            entity_row: true
            entities:
              - entity: sensor.svnas_cpu_utilization_total
                name: Processor
                tap_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.svnas_cpu_utilization_total

              - entity: sensor.svnas_memory_usage_real
                name: Memory - 2GB
                tap_action:
                  action: call-service
                  service: homeassistant.update_entity
                  service_data:
                    entity_id: sensor.svnas_memory_usage_real

          - type: custom:hui-horizontal-stack-card
            cards:
              - type: entities
                entities:
                  - entity: sensor.nas_net_down
                    name: false
                    style: |
                      :host {
                        --paper-item-icon-color: green;
                      }

              - type: entities
                entities:
                  - entity: sensor.nas_net_up
                    name: false
                    style: |
                      :host {
                        --paper-item-icon-color: #385581;
                      }

        footer:
          type: custom:mini-graph-card
          entities:
            - color: "#385581"
              entity: sensor.svnas_network_up
            - color: green
              entity: sensor.svnas_network_down
          align_state: left
          group: false
          points_per_hour: 15
          line_width: 3
          hour24: true
          hours_to_show: 1.5
          show:
            {
              fill: fade,
              icon: false,
              name: false,
              state: false,
              name_adaptive_color: true,
              labels: hover,
              legend: false,
            }
          tap_action:
            action: none
