# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  auth_providers:
    - type: homeassistant

tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

sun:

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

# Includes
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
cover: !include_dir_merge_list covers
light: !include_dir_merge_list lights
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors

lovelace:
  mode: yaml
