# Loads default set of integrations.
application_credentials:
cloud:
counter:
dhcp:
homeassistant_alerts:
history:
logbook:
map:
mobile_app:
my:
network:
person:
ssdp:
system_health:
tag:
timer:
webhook:
zeroconf:
zone:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_reverse_proxy
    - 127.0.0.1
    - ::1

tts:
  - platform: google_translate

# ====
# Integrations
# ====
# Sun
sun:

# Config editor
config_editor:

# Google calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  calendar_access: read_only

# ====
# Includes
# ====
automation: !include_dir_merge_list automation
cover: !include template/cover.yaml
light: !include_dir_merge_list light
script: !include_dir_merge_named script
scene: !include_dir_merge_list scene
template: !include_dir_merge_named template

# ====
# User Interface
# ====
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  dashboards:
    tablet-dashboard:
      mode: yaml
      title: Tablet Dashboard
      show_in_sidebar: true
      filename: ui-tablet.yaml
  resources:
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/config-editor-card/config-editor-card.js
      type: module
