# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: EUR
  time_zone: Europe/Amsterdam
  temperature_unit: C
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  auth_providers:
    - type: homeassistant
  customize:
    person.helena_user:
      entity_picture: "/local/img/people/helena.png"
    person.nancy:
      entity_picture: "/local/img/people/nancy.png"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_reverse_proxy
    - 127.0.0.1
    - ::1

tts:
  - platform: google_translate
    language: nl

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

frontend:
  themes: !include_dir_merge_named themes

browser_mod:
config_editor:
sun:

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

# Includes
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
cover: !include_dir_merge_list covers
light: !include_dir_merge_list lights
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensors
template:
  - sensor: !include_dir_merge_list templates/sensors

camera:
  - platform: mjpeg
    name: Tablet
    mjpeg_url: http://192.168.68.110:2971/camera/stream

person:
  - name: Helena
    id: helena_user
    user_id: !secret user_id_helena
    device_trackers:
      - device_tracker.dn2103
  - name: Nancy
    id: nancy
    user_id: !secret user_id_nancy
    device_trackers:
      - device_tracker.nokia_x20

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

media_player:
  - platform: emby
    host: !secret nas_ip
    api_key: 41d5616f29854f498805e4a8be27160b

trakt_tv:
  language: nl
  sensors:
    upcoming:
      show:
        days_to_fetch: 1
        max_medias: 10

input_boolean:
  guest_mode:
    name: Guest mode
    icon: mdi:account
  prevent_away:
    name: Prevent the away scene from being triggered when empty house is detected
    icon: mdi:home-account

input_select:
  active_scene:
    options:
      - Home
      - Away
      - Watching TV
      - Dinner
      - Goodnight

lovelace:
  mode: yaml
  resources:
    - url: /local/font.css
      type: css

    # HACS
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/config-editor-card/config-editor-card.js
      type: module
