# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

sun:

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

# Includes
group: !include groups.yaml
automation: !include_dir_merge_list automations
light: !include_dir_merge_list lights
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
