# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: EUR
  time_zone: "Europe/Amsterdam"
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  auth_providers:
    - type: homeassistant

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_reverse_proxy
    - 127.0.0.1
    - ::1

tts:
  - platform: google_translate
    language: nl

frontend:
  themes: !include_dir_merge_named themes

sun:

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

# Includes
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
cover: !include_dir_merge_list covers
light: !include_dir_merge_list lights
script: !include_dir_merge_named scripts
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module
