- cal_id: nl.be#holiday@group.v.calendar.google.com
  entities:
    - device_id: feestdagen_in_belgie
      ignore_availability: true
      name: "Feestdagen in Belgi\xEB"
      track: true

- cal_id: qgrdgq2ejb0g7gantms6qtn8g8@group.calendar.google.com
  entities:
    - device_id: afval
      ignore_availability: true
      name: Afval
      track: true

- cal_id: family02450859625082068313@group.calendar.google.com
  entities:
    - device_id: gezin
      ignore_availability: true
      name: Gezin
      track: true

- cal_id: helena.standaert@gmail.com
  entities:
    - device_id: persoonlijk
      ignore_availability: true
      name: Persoonlijk
      track: true

- cal_id: nancy.vanobbergen@gmail.com
  entities:
    - device_id: nancy
      ignore_availability: true
      name: nancy.vanobbergen@gmail.com
      track: true

- cal_id: helena@pau.be
  entities:
    - device_id: work
      ignore_availability: true
      name: Work
      track: true

- cal_id: plcs721r5jds25si3ndgb6uk9c@group.calendar.google.com
  entities:
  - device_id: todoist
    ignore_availability: true
    name: Todoist
