- platform: template
  lights:
    dining_table:
      friendly_name: Eettafel
      level_template: "{{ states('dining_table_brightness')|int }}"
      value_template: "{{ states('dining_table_brightness')|int > 0 }}"
      temperature_template: "{{states('input_number.dining_table_color_temp') | int}}"
      turn_on:
        service: light.turn_on
        target:
          entity_id:
            - light.hanglamp_1
            - light.hanglamp_2
            - light.hanglamp_3
            - light.hanglamp_4
            - light.hanglamp_5
      turn_off:
        service: light.turn_off
        target:
          entity_id:
            - light.hanglamp_1
            - light.hanglamp_2
            - light.hanglamp_3
            - light.hanglamp_4
            - light.hanglamp_5
      set_temperature:
        service: input_number.set_value
        data:
          value: "{{ color_temp }}"
          entity_id: input_number.dining_table_color_temp
      set_level:
        service: input_number.set_value
        data:
          value: "{{ brightness }}"
          entity_id: input_number.dining_table_brightness

    reading_lamp:
      friendly_name: "Leeslamp"
      level_template: "{{ states('reading_lamp_brightness')|int }}"
      value_template: "{{ states('reading_lamp_brightness')|int > 0 }}"
      temperature_template: "{{states('input_number.reading_lamp_color_temp') | int}}"
      turn_on:
        service: light.turn_on
        target:
          entity_id:
            - light.hanglamp_1
            - light.hanglamp_2
            - light.hanglamp_3
            - light.hanglamp_4
            - light.hanglamp_5
      turn_off:
        service: light.turn_off
        target:
          entity_id:
            - light.hanglamp_1
            - light.hanglamp_2
            - light.hanglamp_3
            - light.hanglamp_4
            - light.hanglamp_5
      set_temperature:
        service: input_number.set_value
        data:
          value: "{{ color_temp }}"
          entity_id: input_number.reading_lamp_color_temp
      set_level:
        service: input_number.set_value
        data:
          value: "{{ brightness }}"
          entity_id: input_number.reading_lamp_brightness
