---
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

http_reverse_proxy: 172.0.0.1

wastecollector_city: amsterdam
wastecollector_zip: 1111AA
wastecollector_number: 1
