# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

http_reverse_proxy: 172.0.0.1

# Google calendar
google_client_id: 1234x
google_client_secret: 12345x
