- platform: template
  covers:
    living_room:
      unique_id: living_room
      friendly_name: Rolluiken Woonkamer
      device_class: shutter
      optimistic: true
      position_template: "{{ states('input_number.living_room_cover_position') }}"
      open_cover:
        service: script.open_living_room_covers
      close_cover:
        service: script.close_living_room_covers
      stop_cover:
        service: script.stop_living_room_covers
      set_cover_position:
        service: script.set_position_living_room_covers
        data_template:
          position: "{{ position }}"
