- platform: template
  covers:
    living_room:
      unique_id: living_room
      friendly_name: Rolluiken Woonkamer
      device_class: shutter
      optimistic: true
      open_cover:
        service: script.open_living_room_covers
      close_cover:
        service: script.close_living_room_covers
      stop_cover:
        service: script.pause_living_room_covers
