---
alias: Presence
description: >-
  Turns off all devices when leaving the house
id: "820a790e-db97-43ac-98b5-f5a8a678c6b6"
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.anyone_home
    to: "off"

condition:
  - condition: state
    entity_id: input_boolean.house_mode_guest
    state: "off"

action:
  - delay:
      minutes: 1

  - alias: "Turn off all devices"
    service: script.devices_off
