---
alias: Remote working
id: "42524a80-052a-426d-8f7a-ced76b70491d"
mode: single

trigger:
  - platform: state
    entity_id:
      - input_boolean.house_mode_working_remote
    from: "off"
    to: "on"

condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: "on"

action:
  - service: climate.set_temperature
    data:
      temperature: 21.5
    target:
      entity_id: climate.kantoor

  - delay:
      hours: 8

  - service: climate.set_preset_mode
    data:
      temperature: 21.5
    target:
      entity_id: climate.kantoor

  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.house_mode_working_remote
