title: ""
path: dashboard
icon: mdi:home-analytics
type: custom:grid-layout
layout:
  #default
  grid-gap: var(--custom-layout-card-padding)
  grid-template-columns: repeat(4, 1fr) 0
  grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
  grid-template-areas: |
    "sidebar  .           .         .         ."
    "sidebar  woonkamer   eetkamer  upstairs  ."
    "sidebar  media       other     house     ."
    "sidebar  footer      footer    footer    ."
  mediaquery:
    #phone
    "(max-width: 800px)":
      grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
      grid-template-columns: 0 repeat(2, 1fr) 0
      grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
      grid-template-areas: |
        ".  .           .         ."
        ".  sidebar     sidebar   ."
        ".  woonkamer   eetkamer  ."
        ".  upstairs    .         ."
        ".  media       media     ."
        ".  other       house     ."
        ".  footer      footer    ."
        ".  .           .         ."
    #portrait
    "(max-width: 1200px)":
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(3, 1fr) 0
      grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .         ."
        "sidebar  woonkamer   upstairs  ."
        "sidebar  eetkamer    media     ."
        "sidebar  other       house     ."
        "sidebar  footer      footer    ."
        "sidebar  .           .         ."
cards:
  - type: custom:button-card #extra_styles fix

  #################################################
  #                                               #
  #                    SIDEBAR                    #
  #                                               #
  #################################################

  - type: vertical-stack
    view_layout:
      grid-area: sidebar
    cards:
      - type: custom:button-card
        entity: sensor.template_sidebar
        template: sidebar

      - type: grid
        columns: 5
        cards:
          - type: button
            icon: mdi:information-outline
            tap_action: !include ../popup/sidebar-information.yaml
            hold_action:
              action: none

          - type: button
            icon: mdi:account
            tap_action:
              action: navigate
              navigation_path: /profile
            hold_action:
              action: none

  #################################################
  #                                               #
  #                  WOONKAMER                    #
  #                                               #
  #################################################

  - type: grid
    title: Woonkamer
    view_layout:
      grid-area: woonkamer
    columns: 2
    cards:
      - type: custom:button-card
        entity: light.luchter
        template:
          - light
          - icon_hue
      - type: custom:button-card
        entity: light.reading_lamp
        template:
          - light
          - icon_hue
      - type: custom:button-card
        entity: media_player.samsung_tv
        name: Tv
        state_display: >
          [[[
            if (variables.state == 'playing') {
              return 'Aan';
            }
          ]]]
        hold_action: !include ../popup/tv.yaml
        template:
          - base
          - icon_tv
          - loader

      - type: custom:button-card
        entity: cover.covers
        name: Rolluiken
        template:
          - covers
          - loader

      - type: custom:button-card
        entity: climate.woonkamer
        template:
          - heating

  #################################################
  #                                               #
  #                  EETKAMER                     #
  #                                               #
  #################################################

  - type: grid
    title: Eetkamer
    view_layout:
      grid-area: eetkamer
    columns: 2
    cards:
      - type: custom:button-card
        entity: light.chandelier
        template:
          - light
          - icon_hue
      - type: custom:button-card
        entity: switch.aquarium
        template:
          - base
          - icon_aquarium

  #################################################
  #                                               #
  #                    BOVEN                      #
  #                                               #
  #################################################

  - type: grid
    title: Boven
    view_layout:
      grid-area: upstairs
    columns: 2
    cards:
      - type: custom:button-card
        entity: switch.blanket
        template:
          - base
          - icon_blanket

      - type: custom:button-card
        entity: climate.slaapkamer_lore
        template:
          - heating

      - type: custom:button-card
        entity: climate.slaapkamer_ouders
        template:
          - heating

  #################################################
  #                                               #
  #                   OVERIGE                     #
  #                                               #
  #################################################

  - type: grid
    title: Overige
    view_layout:
      grid-area: other
    columns: 2
    cards:
      - type: custom:button-card
        entity: climate.kantoor
        template:
          - heating

      - type: custom:button-card
        entity: sensor.hp_envy_5000_series
        template:
          - printer

      - type: custom:button-card
        entity: climate.veranda
        template:
          - heating

      - type: custom:button-card
        entity: climate.badkamer
        template:
          - heating

  #################################################
  #                                               #
  #                    HUIS                       #
  #                                               #
  #################################################

  - type: grid
    title: Huis
    view_layout:
      grid-area: house
    columns: 2
    cards:
      - type: custom:button-card
        entity: person.helena_user
        name: Helena
        template: person
        tap_action:
          action: more-info

      - type: custom:button-card
        entity: person.nancy
        name: Nancy
        template: person
        tap_action:
          action: more-info

      - type: custom:button-card
        entity: scene.away
        name: Weg
        hold_action:
          action: none
        template:
          - base
          - icon_away

      - type: custom:button-card
        entity: scene.home
        name: Thuis
        hold_action:
          action: none
        template:
          - base
          - icon_home

  #################################################
  #                                               #
  #                    MEDIA                      #
  #                                               #
  #################################################

  - type: grid
    title: Media
    view_layout:
      grid-area: media
    columns: 1
    cards:
      - type: custom:swipe-card
        start_card: 1
        parameters:
          roundLengths: true
          effect: coverflow
          speed: 650
          spaceBetween: 20
          threshold: 7
          coverflowEffect:
            rotate: 80
            depth: 300
          autoplay:
            delay: 20000
        cards:
          - type: conditional
            conditions:
              - entity: media_player.tv
                state: playing
            card:
              type: custom:button-card
              entity: media_player.tv
              template:
                - conditional_media
                - icon_cast

          - type: conditional
            conditions:
              - entity: media_player.badkamer
                state: playing
            card:
              type: custom:button-card
              entity: media_player.badkamer
              template:
                - conditional_media
                - icon_cast

          - type: conditional
            conditions:
              - entity: media_player.hub
                state: playing
            card:
              type: custom:button-card
              entity: media_player.hub
              template:
                - conditional_media
                - icon_cast

          - type: conditional
            conditions:
              - entity: media_player.kantoor
                state: playing
            card:
              type: custom:button-card
              entity: media_player.kantoor
              template:
                - conditional_media
                - icon_cast

          - type: conditional
            conditions:
              - entity: media_player.living_speaker
                state: playing
            card:
              type: custom:button-card
              entity: media_player.living_speaker
              template:
                - conditional_media
                - icon_cast

          - type: conditional
            conditions:
              - entity: media_player.spotify
                state: playing
            card:
              type: custom:button-card
              entity: media_player.spotify
              template:
                - conditional_media
                - icon_spotify

          - type: conditional
            conditions:
              - entity: media_player.emby_tv
                state: playing
            card:
              type: custom:button-card
              entity: media_player.emby_tv
              template:
                - conditional_media
                - icon_emby

          - type: custom:upcoming-media-card
            entity: sensor.trakt_upcoming_shows
            image_style: fanart
            date: ddmm
            clock: 24
            max: 4
            hide_empty: true
            title_text: $title
            line1_text: $episode
            line2_text: $number
            line3_text: $day, $date $time
            line4_text: $empty
            accent_color: rgba(255, 255, 255, 0.3)
            border_color: rgba(255, 255, 255, 0)
            box_shadows: false
