title: ""
icon: mdi:bed-empty
path: "upstairs"
cards:
  # Blanket
  - type: picture-entity
    entity: switch.60053804840d8e63c409
    image: >-
      https://images.unsplash.com/photo-1572270947869-89e664b0792b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2344&q=80
    show_state: true
    show_name: true
    tap_action:
      action: toggle
    hold_action:
      action: more-info

  # Heating Kids
  - type: vertical-stack
    cards:
      - type: thermostat
        entity: climate.slaapkamer_lore
      - title: Slaapkamer Kinderen
        type: entities
        entities:
          - entity: sensor.slaapkamer_lore_temperature
            name: Temperature
          - entity: sensor.slaapkamer_lore_humidity
            name: Humidity
          - entity: binary_sensor.slaapkamer_lore_open_window
            name: Windows
          - entity: sensor.slaapkamer_lore_heating
            name: Heating
        header:
          type: graph
          entity: sensor.slaapkamer_lore_temperature
          hours_to_show: 24
          detail: 1

  # Heating Parents
  - type: vertical-stack
    cards:
      - type: thermostat
        entity: climate.slaapkamer_ouders
      - title: Slaapkamer Lore
        type: entities
        entities:
          - entity: sensor.slaapkamer_ouders_temperature
            name: Temperature
          - entity: sensor.slaapkamer_ouders_humidity
            name: Humidity
          - entity: binary_sensor.slaapkamer_ouders_open_window
            name: Windows
          - entity: sensor.slaapkamer_ouders_heating
            name: Heating
        header:
          type: graph
          entity: sensor.slaapkamer_ouders_temperature
          hours_to_show: 24
          detail: 1
