title: ""
icon: mdi:incognito
path: monitoring
badges: []
cards:
  # Speedtest
  - type: vertical-stack
    cards:
      - type: button
        tap_action:
          action: call-service
          service: speedtestdotnet.speedtest
        name: Run speedtest
        show_name: true
        show_state: false
        show_icon: true
        icon: mdi:speedometer
      - title: Internet Speed
        type: entities
        entities:
          - entity: sensor.speedtest_download
            name: Download
            secondary_info: last-updated
          - entity: sensor.speedtest_upload
            name: Upload
            secondary_info: last-updated
          - entity: sensor.speedtest_ping
            name: Ping

  # NAS
  - title: Synology DS218
    type: entities
    entities:
      - entity: sensor.svnas_cpu_load_average_15_min
        name: Load Average
      - entity: binary_sensor.svnas_security_status
        name: Security Status
      - entity: sensor.svnas_temperature
        name: Temperature
      - entity: binary_sensor.svnas_update_available
        name: Update Available
      - entity: sensor.svnas_memory_usage_real
        name: Memory Usage (Real)

  # NAS Volume
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.svnas_volume_1_volume_used
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 70
          red: 80
        name: Volume Used
      - type: gauge
        entity: sensor.svnas_cpu_utilization_total
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 80
        name: CPU Utilization

  # NAS Drive 1
  - title: Drive 1
    type: entities
    entities:
      - entity: sensor.svnas_drive_1_status
        name: Status
      - entity: binary_sensor.svnas_drive_1_below_min_remaining_life
        name: Remaining Life
      - entity: binary_sensor.svnas_drive_1_exceeded_max_bad_sectors
        name: Bad Sectors
      - entity: sensor.svnas_drive_1_temperature
        name: Temperature

  # NAS Drive 2
  - title: Drive 2
    type: entities
    entities:
      - entity: sensor.svnas_drive_2_status
        name: Status
      - entity: binary_sensor.svnas_drive_2_below_min_remaining_life
        name: Remaining Life
      - entity: binary_sensor.svnas_drive_2_exceeded_max_bad_sectors
        name: Bad Sectors
      - entity: sensor.svnas_drive_2_temperature
        name: Temperature

  # NAS Network traffic
  - type: vertical-stack
    cards:
      - type: sensor
        entity: sensor.svnas_network_down
        graph: line
        name: Download
      - type: sensor
        entity: sensor.svnas_network_up
        graph: line
        name: Upload
