title: ""
path: overview
icon: mdi:home-analytics
type: custom:grid-layout
layout:
  grid-template-columns: 1fr 1fr
  grid-template-rows: auto
  grid-template-areas: |
    "header header"
    "categories devices"
    "scenes devices"
  mediaquery:
    #phone
    "(max-width: 800px)":
      grid-template-columns: 1fr
      grid-template-rows: auto
      grid-template-areas: |
        "header"
        "scenes"
        "categories"
        "devices"
cards:
  - type: horizontal-stack
    view_layout:
      grid-area: header
    cards:
      - type: "custom:button-card"
        template: edge

      - type: "custom:button-card"
        template: chip_temperature
        variables:
          ulm_chip_temperature_inside: sensor.woonkamer_temperature
          ulm_chip_temperature_outside: sensor.openweathermap_temperature
          ulm_chip_temperature_weather: weather.openweathermap

      - type: "custom:button-card"
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: 🏠
          ulm_chip_icon_state_entity: sensor.people_home

      - type: conditional
        conditions:
          - entity: input_boolean.guest_mode
            state: "on"
        card:
          type: "custom:button-card"
          template: chip_icon_only
          variables:
            ulm_chip_icon_only: 👪

  - type: vertical-stack
    view_layout:
      grid-area: categories
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Categorieën

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: repeat(4, 1fr)
          grid-template-rows: auto
          mediaquery:
            "(max-width: 1024px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /lovelace/presence
              ulm_card_navigate_title: Mensen
              ulm_card_navigate_icon: mdi:account

          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /lovelace/lights
              ulm_card_navigate_title: Lichten
              ulm_card_navigate_icon: mdi:lightbulb

          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /lovelace/climate
              ulm_card_navigate_title: Klimaat
              ulm_card_navigate_icon: mdi:cloud

  - type: vertical-stack
    view_layout:
      grid-area: scenes
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Scènes
        label: "Om snel de sfeer in huis aan te passen"

      - type: grid
        columns: 6
        square: false
        cards:
          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.active_scene
            name: Thuis
            icon: mdi:home-lock-open
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: Home
              ulm_card_vertical_button_color: green

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.active_scene
            name: Weg
            icon: mdi:home-lock
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: Away
              ulm_card_vertical_button_color: red

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.active_scene
            name: TV kijken
            icon: mdi:television-classic
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: Watching TV
              ulm_card_vertical_button_color: purple

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.active_scene
            name: Aan tafel
            icon: mdi:food-turkey
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: Dinner
              ulm_card_vertical_button_color: yellow

          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.active_scene
            name: Slaapwel
            icon: mdi:weather-night
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: Goodnight
              ulm_card_vertical_button_color: blue

  - type: vertical-stack
    view_layout:
      grid-area: devices
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Apparaten
        label: Verander de status van de meest gebruikte slimme apparaten

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: repeat(2, 1fr)
          grid-template-rows: auto
          mediaquery:
            "(max-width: 1024px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_light
            entity: light.eettafel
            variables:
              ulm_card_light_enable_color: true
              ulm_card_light_enable_popup: true

          - type: "custom:button-card"
            template: card_light
            entity: light.leeslamp
            variables:
              ulm_card_light_enable_color: true
              ulm_card_light_enable_popup: true

          - type: "custom:button-card"
            template: card_light
            entity: light.luchter
            variables:
              ulm_card_light_enable_color: true
              ulm_card_light_enable_popup: true

          - type: "custom:button-card"
            template: card_power_outlet
            entity: switch.blanket

          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.woonkamer
            variables:
              ulm_card_thermostat_enable_controls: true

          - type: "custom:button-card"
            template: card_cover_buttons
            variables:
              ulm_card_cover_buttons_name: Rolluiken
              ulm_card_cover_buttons_entity: cover.living_room
