title: ""
path: climate
visible: false
icon: mdi:cloud
type: custom:grid-layout
layout:
  grid-template-columns: 1fr
  grid-template-rows: auto
  grid-template-areas: |
    "header"
    "thermostat"
    "weather"
    "living_room"
    "bathroom"
    "office"
    "veranda"
    "parents"
    "kids"
  mediaquery:
    #tablet
    "(min-width: 800px)":
      grid-template-columns: 1fr 1fr 1fr
      grid-template-rows: auto
      grid-template-areas: |
        "header header header"
        "thermostat thermostat ."
        "weather . ."
        "living_room bathroom office"
        "veranda parents kids"
cards:
  - type: horizontal-stack
    view_layout:
      grid-area: header
    cards:
      - type: "custom:button-card"
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace/overview

      - type: "custom:button-card"
        template: chip_temperature
        variables:
          ulm_chip_temperature_inside: sensor.woonkamer_temperature
          ulm_chip_temperature_outside: sensor.openweathermap_temperature
          ulm_chip_temperature_weather: weather.openweathermap

  - type: vertical-stack
    view_layout:
      grid-area: weather
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Temperatuur
        label: Buiten

      - type: "custom:button-card"
        template: card_weather
        entity: weather.openweathermap

  - type: vertical-stack
    view_layout:
      grid-area: thermostat
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Thermostaat

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 1fr
          grid-template-rows: auto
          mediaquery:
            #tablet
            "(min-width: 800px)":
              grid-template-columns: repeat(2, 1fr)
            "(min-width: 1024)":
              grid-template-columns: repeat(3, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.woonkamer
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.badkamer
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.kantoor
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.veranda
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.slaapkamer_ouders
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.slaapkamer_lore
            variables:
              ulm_card_thermostat_enable_collapse: true
              ulm_card_thermostat_enable_controls: true
              ulm_card_thermostat_enable_hvac_modes: true
              ulm_card_thermostat_enable_popup: true

  - type: vertical-stack
    view_layout:
      grid-area: living_room
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Woonkamer

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.woonkamer_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.woonkamer_humidity

  - type: vertical-stack
    view_layout:
      grid-area: bathroom
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Badkamer

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.badkamer_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.badkamer_humidity

  - type: vertical-stack
    view_layout:
      grid-area: office
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Kantoor

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.kantoor_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.kantoor_humidity

  - type: vertical-stack
    view_layout:
      grid-area: veranda
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Veranda

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.veranda_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.veranda_humidity

  - type: vertical-stack
    view_layout:
      grid-area: parents
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Slaapkamer ouders

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.slaapkamer_ouders_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.slaapkamer_ouders_humidity

  - type: vertical-stack
    view_layout:
      grid-area: kids
    cards:
      - type: "custom:button-card"
        template: card_title
        label: Slaapkamer ouders

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-red)"
              ulm_card_graph_name: Temperatuur
              ulm_card_graph_entity: sensor.slaapkamer_ouders_temperature

          - type: "custom:button-card"
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Vochtigheidsgraad
              ulm_card_graph_entity: sensor.slaapkamer_ouders_humidity
