title: ""
path: devices
visible: false
icon: mdi:devices
type: custom:vertical-layout
cards:
  - type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace/overview

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Woonkamer

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 1fr
          grid-template-rows: auto
          mediaquery:
            #tablet
            "(min-width: 800px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_power_outlet
            entity: switch.tv

          - type: "custom:button-card"
            template: card_power_outlet
            entity: switch.aquarium

          - type: "custom:button-card"
            template: card_media_player
            entity: media_player.tv
            name: Chromecast
            variables:
              ulm_card_media_player_name: Chromecast
              ulm_card_media_player_icon: mdi:television
              ulm_card_media_player_enable_controls: true
              ulm_card_media_player_enable_art: true

          - type: "custom:button-card"
            template: card_media_player
            entity: media_player.home
            name: Google Home
            variables:
              ulm_card_media_player_name: Google Home
              ulm_card_media_player_enable_controls: true
              ulm_card_media_player_enable_art: true
              ulm_card_media_player_enable_volume_slider: true

          - type: "custom:button-card"
            template: card_media_player
            entity: media_player.hub
            name: Google Hub
            variables:
              ulm_card_media_player_name: Google Hub
              ulm_card_media_player_enable_controls: true
              ulm_card_media_player_enable_art: true
              ulm_card_media_player_enable_volume_slider: true

          - type: "custom:button-card"
            template: card_cover_buttons
            variables:
              ulm_card_cover_buttons_name: Rolluiken
              ulm_card_cover_buttons_entity: cover.living_room

      - type: "custom:button-card"
        template: card_title
        name: Kantoor

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 1fr
          grid-template-rows: auto
          mediaquery:
            #tablet
            "(min-width: 800px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_media_player
            entity: media_player.kantoor
            name: Nest mini
            variables:
              ulm_card_media_player_name: Nest mini
              ulm_card_media_player_enable_controls: true
              ulm_card_media_player_enable_art: true
              ulm_card_media_player_enable_volume_slider: true

      - type: "custom:button-card"
        template: card_title
        name: Badkamer

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 1fr
          grid-template-rows: auto
          mediaquery:
            #tablet
            "(min-width: 800px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_media_player
            entity: media_player.badkamer
            name: Home mini
            variables:
              ulm_card_media_player_name: Home mini
              ulm_card_media_player_enable_controls: true
              ulm_card_media_player_enable_art: true
              ulm_card_media_player_enable_volume_slider: true

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Slaapkamer ouders

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: 1fr
          grid-template-rows: auto
          mediaquery:
            #tablet
            "(min-width: 800px)":
              grid-template-columns: repeat(2, 1fr)
        cards:
          - type: "custom:button-card"
            template: card_power_outlet
            entity: switch.blanket
