type: grid
title: Huis
view_layout:
  grid-area: house
columns: 2
cards:
  - type: custom:button-card
    entity: person.helena_user
    name: Helena
    template: person
    tap_action:
      action: more-info

  - type: custom:button-card
    entity: person.nancy
    name: Nancy
    template: person
    tap_action:
      action: more-info

  - type: custom:button-card
    name: Weg
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.away
    hold_action:
      action: none
    template:
      - base
      - icon_away

  - type: custom:button-card
    name: Thuis
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data:
        entity_id: scene.home
    hold_action:
      action: none
    template:
      - base
      - icon_home
