title: ""
path: lights
visible: false
icon: mdi:lightbulb
type: custom:vertical-layout
cards:
  - type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace/overview

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Woonkamer

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_light
            entity: light.leeslamp
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true

          - type: "custom:button-card"
            template: card_light
            entity: light.luchter
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true

          - type: "custom:button-card"
            template: card_light
            entity: light.led
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Eetkamer

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_light
            entity: light.eettafel
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
