type: grid
title: Leefruimte
view_layout:
  grid-area: living-room
columns: 4
cards:
  - type: custom:button-card
    entity: light.luchter
    template:
      - light
      - icon_hue

  - type: custom:button-card
    entity: light.leeslamp
    template:
      - light
      - icon_hue

  - type: custom:button-card
    entity: media_player.samsung_tv
    name: Tv
    state_display: >
      [[[
        if (variables.state == 'playing') {
          return 'Aan';
        }
      ]]]
    hold_action: !include ../popup/tv.yaml
    template:
      - base
      - icon_tv
      - loader

  - type: custom:button-card
    entity: cover.covers
    name: Rolluiken
    template:
      - covers
      - loader

  - type: custom:button-card
    entity: climate.woonkamer
    template:
      - heating

  - type: custom:button-card
    entity: light.eettafel
    template:
      - light
      - icon_hue

  - type: custom:button-card
    entity: switch.aquarium
    template:
      - base
      - icon_aquarium

  - type: custom:button-card
    entity: climate.badkamer
    template:
      - heating
