title: ""
path: presence
visible: false
type: custom:vertical-layout
cards:
  - type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: chip_back
        variables:
          ulm_chip_back_path: /lovelace/overview

      - type: "custom:button-card"
        template: chip_icon_state
        variables:
          ulm_chip_icon_state_icon: 🏠
          ulm_chip_icon_state_entity: sensor.people_home

      - type: conditional
        conditions:
          - entity: input_boolean.guest_mode
            state: "on"
        card:
          type: "custom:button-card"
          template: chip_icon_only
          variables:
            ulm_chip_icon_only: 👪

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: card_title
        name: Aanwezigheid
        label: Personen

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_person
            variables:
              ulm_card_person_entity: person.helena_user
              ulm_card_person_use_entity_picture: true

          - type: "custom:button-card"
            template: card_person
            variables:
              ulm_card_person_entity: person.nancy
              ulm_card_person_use_entity_picture: true

      - type: "custom:button-card"
        template: card_title
        label: Mode

      - type: grid
        columns: 2
        square: false
        cards:
          - type: "custom:button-card"
            template: card_input_boolean
            entity: input_boolean.guest_mode
            name: Gasten aanwezig
          - type: "custom:button-card"
            template: card_input_boolean
            entity: input_boolean.working_from_home_mode
            name: Thuiswerken
