type: grid
title: Boven
view_layout:
  grid-area: upstairs
columns: 2
cards:
  - type: custom:button-card
    entity: switch.blanket
    template:
      - base
      - icon_blanket

  - type: custom:button-card
    entity: climate.slaapkamer_lore
    template:
      - heating

  - type: custom:button-card
    entity: climate.slaapkamer_ouders
    template:
      - heating
