icon_blanket:
  styles:
    custom_fields:
      icon:
        - width: 82%
        - margin-left: 1%
        - margin-top: 6%
        - fill: >
            [[[ return variables.state === 'on' ? '#72757c' : '#9da0a2'; ]]]
  custom_fields:
    icon: >
      [[[
        const state = (variables.state === 'on' && variables.timeout < 2000) ? 'on' : null;
        return `
          <svg viewBox="0 0 24 24">
            <style>
              @keyframes on {
                from {
                  opacity: 0.5;
                  transform: scale(0.6);
                }
                100% {
                  opacity: 1;
                }
              }ov
              .on {
                animation: on 0.8s cubic-bezier(0.25, 1, 0.5, 1);
                transform-origin: center;
              }
            </style>
            <path  class="${state}" d="M20 2H7C4.243 2 2 4.243 2 7v10c0 2.757 2.243 5 5 5h12c1.654 0 3-1.346 3-3s-1.346-3-3-3H6v2h13a1 1 0 0 1 0 2H7c-1.654 0-3-1.346-3-3s1.346-3 3-3h13c1.103 0 2-.897 2-2V4c0-1.103-.897-2-2-2zM4 13h.003L4 13.002V13z"/>
          </svg>
        `;
      ]]]
