---
alias: Coming home
id: coming_home
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.anyone_home
    to: "on"

action:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"

  - service: input_select.select_option
    data:
      option: Home
    target:
      entity_id: input_select.heating_modes

  - scene: scene.home
