---
alias: Heating
id: heating
description: >-
  When we leave home, we turn off the heating and when we come home, we turn it back on.
mode: single
trigger:
  - platform: numeric_state
    entity_id: zone.home
    above: 0
    id: turn_on

  - platform: numeric_state
    entity_id: zone.home
    below: 1
    id: turn_off

  - platform: time
    at: "00:00:00"
    id: reset

condition:
  - condition: state
    entity_id: input_boolean.house_mode_guest
    state: "off"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'turn_off' }}"
        sequence:
          - action: climate.set_hvac_mode
            data:
              hvac_mode: "off"
            target:
              entity_id:
                - climate.office_heater
                - climate.heating_boys
                - climate.heating_girls
          - action: climate.set_preset_mode
            data:
              preset_mode: "away"
            target:
              entity_id:
                - climate.woonkamer
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'turn_on' or trigger.id == 'reset' }}"
        sequence:
          - action: climate.set_hvac_mode
            data:
              hvac_mode: "auto"
            target:
              entity_id:
                - climate.woonkamer
