---
alias: Heating (Working from home)
id: heating_working_from_home
mode: single

trigger:
  - platform: state
    entity_id:
      - input_boolean.working_from_home
    from: "off"
    to: "on"

condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: "on"

action:
  - service: climate.turn_on
    target:
      entity_id: climate.kantoor
  - service: climate.set_temperature
    data:
      temperature: 21.5
    target:
      entity_id: climate.kantoor
  - delay:
      hours: 8
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.working_from_home
