---
alias: Leaving the house
id: leaving_the_house
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.anyone_home
    to: "off"

action:
  - delay:
      minutes: 1

  - condition: state
    entity_id: input_boolean.house_mode_guest
    state: "off"

  - service: input_select.select_option
    data:
      option: Away
    target:
      entity_id: input_select.heating_modes

  - scene: scene.away
