---
alias: Turn off night mode
id: turn_off_night_mode
mode: single

trigger:
  - platform: time_pattern
    minutes: "/10"

condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: "on"

  - condition: state
    entity_id: binary_sensor.anyone_home
    state: "on"

  - condition: or
    conditions:
      - condition: time
        after: "07:00:00"
        before: "07:10:00"
      - condition: and
        conditions:
          - condition: time
            before: "07:10:00"
          - condition: sun
            after: sunrise

action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.night_mode
