---
alias: TV backlight on
id: tv_backlight_on
mode: single

trigger:
  - platform: state
    entity_id: media_player.samsung_tv
    to: "on"

action:
  - service: light.turn_on
    target:
      entity_id: light.led
