- platform: template
  sensors:
    anyone_home:
      device_class: presence
      friendly_name: "Anyone Home"
      value_template: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
