---
title: Security
path: security
icon: fas:video
type: custom:horizontal-layout
layout:
  max_width: 1600
  max_cols: 1
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
        template: card_title
        name: Security

      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: repeat(2, 1fr)
          grid-template-rows: auto
          mediaquery:
            "(max-width: 800px)":
              grid-template-columns: 1fr
              grid-template-rows: auto
        cards:
          - type: picture-entity
            entity: camera.tuin
            camera_view: live
            tap_action:
              action: call-service
              service: camera.snapshot
              service_data:
                entity_id: camera.tuin
                filename: '/shared/tuin-{{ now().strftime("%Y-%m-%d-%H%M%S") }}.jpg'

          - type: picture-entity
            entity: camera.veranda
            camera_view: live
            tap_action:
              action: call-service
              service: camera.snapshot
              service_data:
                entity_id: camera.veranda
                filename: '/shared/lsccamera.lsc_smart_indoor_camera-{{ now().strftime("%Y-%m-%d-%H%M%S") }}.jpg'
